// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodo struct {
	ID string `json:"id"`
}

type NewTodo struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type Todo struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
