// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodo struct {
	ID int `json:"id"`
}

type NewTodo struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type Todo struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Desc   string `json:"desc"`
	IsDone bool   `json:"is_done"`
}

type UpdateTodo struct {
	ID     int     `json:"id"`
	Title  *string `json:"title"`
	Desc   *string `json:"desc"`
	IsDone *bool   `json:"is_done"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
