// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodo struct {
	ID int `json:"id"`
}

type DeleteUser struct {
	ID int `json:"id"`
}

type NewTodo struct {
	Title  string `json:"title"`
	Desc   string `json:"desc"`
	UserID int    `json:"user_id"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Todo struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Desc   string `json:"desc"`
	IsDone bool   `json:"is_done"`
	UserID int    `json:"user_id"`
}

type UpdateTodo struct {
	ID     int     `json:"id"`
	Title  *string `json:"title"`
	Desc   *string `json:"desc"`
	IsDone *bool   `json:"is_done"`
}

type UpdateUser struct {
	ID   int     `json:"id"`
	Name *string `json:"name"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
